- type: web
    plan: free
    name: FADEDSTRING
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 server.py & python3 -m FADEDSTRING
 repo:
https://github.com/Adithakur008/DESTROYER-STRING_GEN  
    branch: master
    envVars:
      - key: API_ID
        sync: false
        - key: API_HASH
        sync: false
      - key: BOT_TOKEN 
        sync: false
      - key: OWNER_ID 
        sync: 7557718680
      - key: MONGO_URL
        sync: false    
    autoDeploy: false
